#!/bin/bash

debug() {
	[ -n "$DEBUG" ] && echo "$*"
}

SUMCMD='sha256sum'
DELETE=""
RENAME="yes"

while [ -n "$1" ]; do
	case "$1" in
		"--delete" ) RENAME=""; DELETE="-delete" ;;
		* )
			DEV_SNAPSHOT="$1"
			if [ ! -d "$DEV_SNAPSHOT" ]; then
				echo "Cannot check un-existing snapshot"
				exit 1
			fi
		;;
	esac
	shift
done


if [ -n "$(find . -name "$DEV_SNAPSHOT""/*"".lzma" )" ]; then
for BLOCK_FILE in "$DEV_SNAPSHOT"/*".lzma"; do

	F="$(basename "$BLOCK_FILE" ".lzma")"
	FILE_PAD="${F%%_*}"
	FILE_SUM="${F##*_}"

	ERROR=""
	if [ -z "$FILE_PAD" ]; then ERROR="$ERROR No File Pad"; fi
	if [ -z "$FILE_SUM" ]; then ERROR="$ERROR No File Sum"; fi

	if [ -z "$ERROR" ]; then
		SUM="$(plzip -d -c "$BLOCK_FILE" | $SUMCMD | tr -d ' -')"

		if [ "$SUM" != "$FILE_SUM" ]; then ERROR="$ERROR Incorrect Sum"; fi
	fi

	if [ ! -z "$ERROR" ]; then
		echo "$BLOCK_FILE - $ERROR"

		if [ -n "$RENAME" ]; then
			mv "$BLOCK_FILE" "$BLOCK_FILE.incorrect"
			$BLOCK_FILE="$BLOCK_FILE.incorrect"
		fi

		DEV_FOLDER="$(dirname "$DEV_SNAPSHOT")"
		find "$DEV_FOLDER" -xdev -samefile "$BLOCK_FILE" \! -name "*.lzma.incorrect" $DELETE
	fi

done
else
	echo "Cannot check un-existing snapshot files"
fi

