#!/bin/bash

debug() {
	[ -n "$DEBUG" ] && echo "$*"
}

DEV_SNAPSHOT="$1"
if [ ! -d "$DEV_SNAPSHOT" ]; then
	echo "Cannot de-bloinck un-existing snapshot"
	exit 1
fi

# TODO: we should check that we have all the chuncks before starting to decompress
# 

for BLOCK_FILE in "$DEV_SNAPSHOT"/*".lzma"; do
	plzip -d -c "$BLOCK_FILE"
done

