#!/bin/bash

debug() {
	[ -n "$DEBUG" ] && echo "$*" >&2
}

usage(){
	(
	echo "Usage: $0 [--check|--no-check] machine/block_dev/yyyy-mm-dd__hh-mm-ss/ > dest_file"
	echo "--check: verify checksum before decompressing (default)"
	echo "--no-check: skip verification of checksum"
	while [ -n "$1" ]; do
		echo "$1"
		shift
	done
	) >&2

}

# CMD
PLDEZIP="plzip -q -c -d "
SUMCMD='sha256sum'

CHECK="yes"
DEV_SNAPSHOT=""

# In Megabytes
SIZE="100"

# Local config
if [ -f "./config" ]; then
	. ./config
fi


while [ -n "$1" ]; do

	case "$1" in
		"-c" | "--check" )	CHECK="yes";;
		"-nc" | "--no-check" )	CHECK="";;
		"--nodezip" )	PLDEZIP="tee";;
		* )
		DEV_SNAPSHOT="$1"
		if [ ! -d "$DEV_SNAPSHOT" ]; then
			usage "Cannot de-bloinck un-existing snapshot"
			exit 1
		fi
		;;
	esac
	shift
done


# TODO: we should check that we have all the chuncks before starting to decompress and that they are OK
# 

if [ -n "$( find "$DEV_SNAPSHOT" -wholename "*.lzma" )" ]; then

	if [ -n "$CHECK" ]; then
		for BLOCK_FILE in $( find "$DEV_SNAPSHOT" -wholename "*.lzma" | sort ); do
			SUM="$($PLDEZIP "$BLOCK_FILE" | $SUMCMD | tr -d ' -')"
			if [ "${BLOCK_FILE//$SUM/}" == "$BLOCK_FILE" ]; then
				echo "Verification of $BLOCK_FILE failed, you should run the 'check' script before decompressing" >&2
				exit 1
			fi
		done
	fi

	for BLOCK_FILE in $( find "$DEV_SNAPSHOT" -wholename "*.lzma" | sort ); do
		#$PLDEZIP "$BLOCK_FILE"
		dd if="$BLOCK_FILE" bs="$SIZE""M"
	done | $PLDEZIP
else
	usage "Cannot de-bloinck un-existing snapshot files"
fi

