#!/bin/bash

debug() {
	[ -n "$DEBUG" ] && echo "$*"
}

DEV_SNAPSHOT="$1"
if [ ! -d "$DEV_SNAPSHOT" ]; then
	echo "Cannot de-bloinck un-existing snapshot"
	exit 1
fi


for BLOCK_FILE in "$DEV_SNAPSHOT"/*; do

	dd status=noxfer if="$BLOCK_FILE" bs=5M 2> /dev/null |\
		plzip -d -c
done

