#!/bin/bash

SCRIPTDIR="$(dirname "$0")"
cd "$SCRIPTDIR"

for date in  $(ls -1  */*.lzma | sed -e "s/.*\(20[0-9][0-9]-[01][0-9]-[0-3][0-9]\).*/\1/g" | sort -u); do
	sizes="$(find -name "*$date*" -printf "%s ")"
	sizes="${sizes// /+}0"
	if [ -n "$1" ]; then
		ls -lSr */*$date*
	fi
	echo "$date : $(( $(( $sizes )) / 1024 / 1024)) MB"
done
